/**
 * @fileoverview Defines and exports the Role model for MongoDB.
 * @module RoleModel
 * @namespace RoleModel
 * @description Defines and exports the Role model for MongoDB.
 * @requires mongoose - MongoDB object modeling tool.
 * @see {@link https://mongoosejs.com/docs/models.html|mongoose}
 */

// Import dependencies
const mongoose = require("mongoose");

/**
 * @typedef {Object} RoleSchema
 * @description Defines the structure of the Role document in MongoDB.
 * @property {string} name - The title of the role.
 * @property {mongoose.Schema.Types.ObjectId} _id - The unique identifier of the role, automatically generated by MongoDB.
 */

/**
 * @constructor
 * @description Defines the Role model in MongoDB.
 * @param {RoleSchema} roleSchema - Defines the structure of the Role document in MongoDB.
 * @exports Role
 */
const Role = mongoose.model(
  "Role",
  new mongoose.Schema({
    /**
     * @type {string}
     * @description The title of the role.
     * @required
     */
    name: {
      type: String,
      required: true,
    },
  })
);

module.exports = Role;
