/**
 * @fileoverview Defines and exports the Role model for MongoDB.
 * @requires mongoose - MongoDB object modeling tool.
 *
 */

// Import dependencies
const mongoose = require("mongoose");

/**
 * @class Role
 * @description Defines the structure of the Role document in MongoDB.
 * @see {@link https://mongoosejs.com/docs/models.html|mongoose}
 * @property {string} name - The title of the role.
 * @property {mongoose.Schema.Types.ObjectId} _id - The unique identifier of the role, automatically generated by MongoDB.
 */

const Role = mongoose.model(
  "Role",
  new mongoose.Schema({
    /**
     * @type {string}
     * @description The title of the role.
     * @required
     */
    name: {
      type: String,
      required: true,
    },
  })
);

// Export the Role model
module.exports = Role;
