/**
 * @fileoverview Defines and exports the User model for MongoDB.
 * @requires mongoose - MongoDB object modeling tool.
 *
 */

// Import dependencies
const mongoose = require("mongoose");

/**
 * @class User
 * @description Defines the structure of the User document in MongoDB.
 * @see {@link https://mongoosejs.com/docs/models.html|mongoose}
 * @property {string} username - The unique username of the user. Min length is 3 and max length is 50.
 * @property {string} email - The unique email address of the user. Max length is 320.
 * @property {string} password - The hashed password of the user. Min length is 8 and max length is 128.
 * @property {string} status - The account status of the user. Can be either "Pending" or "Active". Default is "Pending".
 * @property {string} confirmationCode - The unique confirmation code for account activation or password recovery.
 * @property {Array} roles - The roles assigned to the user.
 * @property {string} createdAt - The timestamp of the user creation.
 * @property {string} updatedAt - The timestamp of the last user update.
 * @property {mongoose.Schema.Types.ObjectId} _id - The unique identifier of the user, automatically generated by MongoDB.
 */

const User = mongoose.model(
  "User",
  new mongoose.Schema(
    {
      /**
       * @type {string}
       * @description The unique username of the user.
       */
      username: {
        type: String,
        minlength: 3,
        maxlength: 50,
        unique: true,
        required: true,
      },
      /**
       * @type {string}
       * @description The unique email address of the user.
       */
      email: {
        type: String,
        maxlength: 320,
        unique: true,
        required: true,
      },
      /**
       * @type {string}
       * @description The hashed password of the user.
       */
      password: {
        type: String,
        minlength: 8,
        maxlength: 128,
        required: true,
      },
      /**
       * @type {string}
       * @description The account status of the user.
       */
      status: {
        type: String,
        enum: ["Pending", "Active"],
        default: "Pending",
      },
      /**
       * @type {string}
       * @description The unique confirmation code for account activation or password recovery.
       */
      confirmationCode: {
        type: String,
        unique: true,
      },
      /**
       * @type {Array}
       * @description The roles assigned to the user.
       */
      roles: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Role",
        },
      ],
    },
    {
      /**
       * @type {boolean}
       * @description Enable timestamps for createdAt and updatedAt fields.
       */
      timestamps: true,
    }
  )
);

// Export the User model
module.exports = User;
